script:
- skip
stages:
- build
- deploy
jobs:
  include:
  - stage: build
    name: Build
    script:
    - bash ./containthedocs-cleanbuild.sh
    before_deploy:
    - cd docs/_build/html
    - ls
    - tar -zcf ${TRAVIS_BUILD_DIR}${REPO}-${TRAVIS_BUILD_NUMBER}.tar.gz ./
    deploy:
      provider: releases
      tag_name: 1.0.${TRAVIS_BUILD_NUMBER}
      api_key:
        secure: w500V7RILZfxx8n9l8+9S1gnqugatCESe+fK4LVH2hCO6hw2GZ8l/fmIW6jmV/zA1/CR4D25HnP7mMXzjrnjk9H8nFVIQvDEtgDvqsSlM8Z2KKKODws8JU3B4r7lfRFowzEQAnwJ9EXaJtCnjtpYnZ+s4d8vMR9MtLQJqPHVCD0hvoghyDj1qckVgAZC5Qc1XpPx8j08cfWIADqktP6sHHZdYbq2zcpuU0ROUAxsLnFmDXreQxVI+HU8q7c2FjKycve6le262FJ+DsJISuG6fsXHCJAZ7cABm4OWcF+BNgzhdyTo5MMvxjkI1uSvIlGHBj9MeAmzlQb53xLZhWeF1FCu/3EYcFEp1/Ea5lsIMRr6UUU7gegm3OCefH6/ergJd8z/0B52id8iw1mx/sIj9glacsj4qtF6F6k36yVqTPNP3HesrsBpo+hubqEoerFeZtfvl7mEaHusWj7Bqc2u5PuFKqePKM2i5ddpZLO2hWorYbsjXMN8L6mgtyWam5kEx9bsb6Bvh8utqvLBSiqGmwROHf0eWu3h/3f/AiW+2BDhSi89dCEpS1k4z66S3qyGNDgQJ6MRzTIiDMzsluWMuRm8Q0ILbvnzz+6DpL52RKq3Jq5waMJ4RqVmvWYvHptQ4pSJTMuUBEKWchMY/3vzmWG/4hz0JUeVuTKgWX5zDOE=
      file: "${TRAVIS_BUILD_DIR}${REPO}-${TRAVIS_BUILD_NUMBER}.tar.gz"
      on:
        repo: nginxinc/nginx-controller-lab
      cleanup: 'false'
